services:
  - type: web
    name: fairfare-api
    runtime: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: fairfare
      - key: CORS_ORIGINS
        value: "*"
